CREATE DATABASE micro_blog;
USE micro_blog;

CREATE TABLE user(
    id INT NOT NULL AUTO_INCREMENT,
    nick VARCHAR(20)NOT NULL,
    email VARCHAR(30) NOT NULL,
    password VARCHAR(32) NOT NULL,
    PRIMARY KEY(id)
) ENGINE = MyISAM;

CREATE TABLE post(
    id INT NOT NULL AUTO_INCREMENT,
    text VARCHAR(200) NOT NULL,
    author VARCHAR(20) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = MyISAM;